quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}

# Liquibase
quarkus.liquibase.migrate-at-start=true

