# Common
quarkus.http.port=${PORT:8080}
quarkus.datasource.db-kind=postgresql
quarkus.oidc.application-type=service

# Liquibase
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.xml

# OpenAPI / Swagger UI
quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=bearerAuth
quarkus.smallrye-openapi.jwt-bearer-format=JWT
quarkus.swagger-ui.path=/swagger-ui

# Dev
%dev.quarkus.datasource.username=${POSTGRES_USER:tixie}
%dev.quarkus.datasource.password=${POSTGRES_PASSWORD:tixie}
%dev.quarkus.datasource.jdbc.url=${JDBC_URL:jdbc:postgresql://localhost:5432/tixie}
%dev.quarkus.oidc.auth-server-url=${OIDC_AUTH_SERVER_URL:http://localhost:8180/realms/tixie}
%dev.quarkus.oidc.client-id=${OIDC_CLIENT_ID:tixie-browser}
%dev.quarkus.swagger-ui.always-include=true

# Prod
%prod.quarkus.datasource.username=${POSTGRES_USER}
%prod.quarkus.datasource.password=${POSTGRES_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${JDBC_URL}
%prod.quarkus.oidc.auth-server-url=${OIDC_AUTH_SERVER_URL}
%prod.quarkus.oidc.client-id=${OIDC_CLIENT_ID}
%prod.quarkus.swagger-ui.always-include=${SWAGGER_UI_ENABLED:false}
