package com.tixie.authz;

public enum Permission {
    COMPANY_READ,
    COMPANY_UPDATE,
    COMPANY_DELETE,
    COMPANY_MANAGE_USERS,
    COMPANY_MANAGE_ROLES,

    GROUP_READ,
    GROUP_CREATE,
    GROUP_UPDATE,
    GROUP_DELETE,
    GROUP_MANAGE_MEMBERS,

    PROJECT_READ,
    PROJECT_CREATE,
    PROJECT_UPDATE,
    PROJECT_DELETE,
    PROJECT_MANAGE_MEMBERS,
    PROJECT_MANAGE_STATUSES,

    ISSUE_READ,
    ISSUE_CREATE,
    ISSUE_UPDATE,
    ISSUE_DELETE,
    ISSUE_TRANSITION,
    ISSUE_ASSIGN,
    ISSUE_MANAGE_GRANTS
}
